# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oftenaskedquestion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='oftenaskedquestion',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='recommend_courses',
        ),
        migrations.DeleteModel(
            name='OftenAskedQuestion',
        ),
    ]
